### ISSUE TITLE
[Question] Windows Support

### ISSUE THREAD

**Issue by ghost** [Francesco149/fgohook#1]
Hello there, 
Legendary work you have here, I'm wondering if you will make a Windows port for this?

**Comment by Francesco149** [comment]
if you mean making it buildable on windows, you just have to figure out the "building" step in the readme on windows. the NDK is available for windows and it shouldn't be much different to use it there. as for usage, it should be the same - adb is also available on windows.

by the way i have no idea if this hook still works on current version as I haven't checked the game in months

**Comment by Francesco149** [comment]
... if you can't figure it out you can always use WSL or MSYS and it should be able to run the build.sh script exactly as described in the readme as long as you have the NDK

**Comment by ghost** [comment]
I got the thing compiled, but I can't get `adb root` root to work, maybe I'll try again some other day. Do you know if there's other ways that I can get FGO's traffic? So far I can only see the AssetStorages from JP and NA, I can't see any of the JSON traffic.

**Comment by Francesco149** [comment]
adb root requires root. if you think your device is rooted then I have no idea why it wouldnt work

**Comment by ghost** [comment]
I'll close this ticket for now. I'll come back another time once I have more time (university is taking up too much of my time right now).
